/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#141313',
        'surface-dim': '#141313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2b2a2a',
        'surface-container-highest': '#353434',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c7c7',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#8e9192',
        'outline-variant': '#444748',
        primary: '#c9c6c5',
        'on-primary': '#313030',
        'primary-container': '#0b0b0b',
        'on-primary-container': '#7b7979',
        'inverse-primary': '#5f5e5e',
        secondary: '#c6c6c7',
        'on-secondary': '#2f3131',
        'secondary-container': '#454747',
        'on-secondary-container': '#b4b5b5',
        success: '#22C55E',
        'electric-blue': '#00E5FF',
        surface: '#141313',
        'surface-variant': '#353434',
        error: '#ffb4ab',
        'error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '48px',
        gutter: '24px',
        'container-max': '1440px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        unit: '4px',
      },
      fontFamily: {
        display: ['Anton', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '1.0', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.1', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-lg-mobile': ['36px', { lineHeight: '1.1', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.0', fontWeight: '600' }],
      },
      keyframes: {
        'pulse-blue': {
          '0%': { transform: 'scaleX(0)', opacity: '0.5' },
          '50%': { transform: 'scaleX(1)', opacity: '1' },
          '100%': { transform: 'scaleX(0)', opacity: '0.5' },
        },
      },
      animation: {
        'pulse-blue': 'pulse-blue 3s infinite ease-in-out',
      },
    },
  },
  plugins: [],
}
